#!/usr/bin/env node
/* eslint-disable no-console */

// Simple Express server for web-based setup
require('dotenv').config({ path: '.env.local' });

const fs = require('node:fs');
const express = require('express');
const path = require('path');
const { env } = require('node:process');

const {
  Client,
  Teams,
  Users,
  Databases,
  ID,
  Permission,
  Role
} = require('node-appwrite');

const app = express();
app.use(express.json());
app.use(express.urlencoded({ extended: true }));

const APPWRITE_ENDPOINT = env.APPWRITE_ENDPOINT;
const APPWRITE_PROJECT_ID = env.APPWRITE_PROJECT_ID;
const APPWRITE_API_KEY = env.APPWRITE_API_KEY;
const DB_ID = env.APPWRITE_DATABASE_ID || 'pms_db';
const COL_ORGS = 'pms_organizations';
const COL_USERS = 'pms_users';

if (!APPWRITE_ENDPOINT || !APPWRITE_PROJECT_ID || !APPWRITE_API_KEY) {
  console.error('Missing required envs: APPWRITE_ENDPOINT, APPWRITE_PROJECT_ID, APPWRITE_API_KEY');
  console.error('Please create a .env.local file with your Appwrite credentials.');
  process.exit(1);
}

const client = new Client()
  .setEndpoint(APPWRITE_ENDPOINT)
  .setProject(APPWRITE_PROJECT_ID)
  .setKey(APPWRITE_API_KEY);

const teams = new Teams(client);
const users = new Users(client);
const databases = new Databases(client);

function slugify(s) {
  // Create a slug and ensure it fits within Appwrite's 36-char limit
  // We need to reserve 4 chars for 'org_' prefix, leaving 32 chars for the slug
  let slug = String(s)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/(^_|_$)/g, '');

  // Truncate to 32 chars to leave room for 'org_' prefix (total 36 chars max)
  if (slug.length > 32) {
    slug = slug.substring(0, 32);
  }

  return slug;
}

/**
 * Update or create .env.local file with organization info
 * @param {string} orgName - Organization name
 * @param {string} orgTeamId - Organization team ID
 */
function updateEnvFile(orgName, orgTeamId) {
  const envPath = path.join(process.cwd(), '.env.local');
  let envContent = '';

  // Read existing .env.local if it exists
  if (fs.existsSync(envPath)) {
    envContent = fs.readFileSync(envPath, 'utf8');
  }

  // Parse existing env vars
  const envVars = {};
  envContent.split('\n').forEach(line => {
    const trimmed = line.trim();
    if (trimmed && !trimmed.startsWith('#')) {
      const [key, ...valueParts] = trimmed.split('=');
      if (key) {
        envVars[key.trim()] = valueParts.join('=').trim();
      }
    }
  });

  // Update with new values
  envVars['ORG_NAME'] = orgName;
  envVars['ORG_TEAM_ID'] = orgTeamId;

  // Ensure these exist (keep if already set)
  if (!envVars['APPWRITE_ENDPOINT']) {
    envVars['APPWRITE_ENDPOINT'] = APPWRITE_ENDPOINT || 'https://cloud.appwrite.io/v1';
  }
  if (!envVars['APPWRITE_PROJECT_ID']) {
    envVars['APPWRITE_PROJECT_ID'] = APPWRITE_PROJECT_ID || '';
  }
  if (!envVars['APPWRITE_API_KEY']) {
    envVars['APPWRITE_API_KEY'] = APPWRITE_API_KEY || '';
  }
  if (!envVars['APPWRITE_DATABASE_ID']) {
    envVars['APPWRITE_DATABASE_ID'] = DB_ID;
  }
  if (!envVars['APPWRITE_BUCKET_DOCS']) {
    envVars['APPWRITE_BUCKET_DOCS'] = 'pms-project-docs';
  }
  if (!envVars['APPWRITE_BUCKET_VERSIONS']) {
    envVars['APPWRITE_BUCKET_VERSIONS'] = 'pms-doc-versions';
  }
  if (!envVars['APPWRITE_INVITE_REDIRECT']) {
    envVars['APPWRITE_INVITE_REDIRECT'] = 'http://localhost:3000/auth/callback';
  }

  // Build new env content with comments
  const newEnvContent = `# Appwrite Configuration
APPWRITE_ENDPOINT=${envVars['APPWRITE_ENDPOINT']}
APPWRITE_PROJECT_ID=${envVars['APPWRITE_PROJECT_ID']}
APPWRITE_API_KEY=${envVars['APPWRITE_API_KEY']}
APPWRITE_DATABASE_ID=${envVars['APPWRITE_DATABASE_ID']}

# Storage Buckets
APPWRITE_BUCKET_DOCS=${envVars['APPWRITE_BUCKET_DOCS']}
APPWRITE_BUCKET_VERSIONS=${envVars['APPWRITE_BUCKET_VERSIONS']}

# Organization Configuration (Auto-generated by setup)
ORG_NAME=${envVars['ORG_NAME']}
ORG_TEAM_ID=${envVars['ORG_TEAM_ID']}

# Teams Bootstrap
APPWRITE_INVITE_REDIRECT=${envVars['APPWRITE_INVITE_REDIRECT']}
`;

  // Write to file
  fs.writeFileSync(envPath, newEnvContent, 'utf8');
  console.log('✓ Updated .env.local with organization configuration');
}

async function ensureTeam(teamId, name) {
  try {
    const team = await teams.get(teamId);
    return { exists: true, team };
  } catch (e) {
    if (e && e.code === 404) {
      const team = await teams.create(teamId, name);
      return { exists: false, team };
    } else {
      throw e;
    }
  }
}

async function ensureOrgDoc(orgTeamId, name) {
  const code = slugify(name);
  try {
    const doc = await databases.createDocument(DB_ID, COL_ORGS, ID.unique(), {
      name,
      code,
      isActive: true
    });
    return { created: true, doc };
  } catch (e) {
    if (e && e.code === 409) {
      return { created: false, message: 'Organization document already exists' };
    }
    if (e && e.code === 404) {
      throw new Error('pms_organizations collection not found. Run setup:collections first.');
    }
    throw e;
  }
}

async function createAdminUser(orgTeamId, adminData) {
  // 1. Create user account
  const user = await users.create(
    ID.unique(),
    adminData.email,
    undefined, // phone
    adminData.password,
    `${adminData.firstName} ${adminData.lastName}`
  );

  // 2. Add admin label to user
  try {
    await users.updateLabels(user.$id, ['admin']);
    console.log('✓ Admin label added to user');
  } catch (e) {
    console.error('Failed to add admin label:', e.message);
    throw e;
  }

  // 3. Add to team (for org membership only, no roles)
  try {
    await teams.createMembership(
      orgTeamId,
      [], // No roles - just membership
      undefined, // email
      user.$id, // userId
      undefined, // phone
      '', // url
      `${adminData.firstName} ${adminData.lastName}`
    );
    console.log('✓ User added to team:', orgTeamId);
  } catch (e) {
    console.log("Failed to add user to team:", e);
    console.warn('Could not add to team:', e.message);
  }

  // 4. Create profile with label-based permissions
  const permissions = [
    Permission.read(Role.user(user.$id)),
    Permission.read(Role.team(orgTeamId)),
    Permission.update(Role.user(user.$id)),
    Permission.update(Role.label('admin')),
    Permission.delete(Role.label('admin')),
  ];

  await databases.createDocument(
    DB_ID,
    COL_USERS,
    ID.unique(),
    {
      accountId: user.$id,
      organizationId: orgTeamId,
      email: adminData.email,
      username: adminData.username,
      firstName: adminData.firstName,
      lastName: adminData.lastName,
      otherNames: adminData.otherNames || '',
      status: 'active',
      title: 'System Administrator',
      timezone: 'Africa/Kampala'
    },
    permissions
  );

  return user;
}

// Serve setup page
app.get('/', (req, res) => {
  res.send(`
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>NREP PMS Setup</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      min-height: 100vh;
      padding: 20px;
      display: flex;
      align-items: center;
      justify-content: center;
    }
    .container {
      background: white;
      border-radius: 12px;
      box-shadow: 0 20px 60px rgba(0,0,0,0.3);
      max-width: 600px;
      width: 100%;
      padding: 40px;
    }
    h1 {
      color: #333;
      margin-bottom: 10px;
      font-size: 28px;
    }
    .subtitle {
      color: #666;
      margin-bottom: 30px;
      font-size: 14px;
    }
    .section {
      margin-bottom: 30px;
      padding-bottom: 30px;
      border-bottom: 1px solid #e0e0e0;
    }
    .section:last-of-type {
      border-bottom: none;
      padding-bottom: 0;
    }
    .section-title {
      font-size: 18px;
      font-weight: 600;
      color: #667eea;
      margin-bottom: 15px;
    }
    .form-group {
      margin-bottom: 20px;
    }
    label {
      display: block;
      margin-bottom: 5px;
      font-weight: 500;
      color: #333;
      font-size: 14px;
    }
    input {
      width: 100%;
      padding: 12px;
      border: 2px solid #e0e0e0;
      border-radius: 6px;
      font-size: 14px;
      transition: border-color 0.3s;
    }
    input:focus {
      outline: none;
      border-color: #667eea;
    }
    .optional {
      color: #999;
      font-weight: 400;
      font-size: 12px;
    }
    button {
      width: 100%;
      padding: 14px;
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      color: white;
      border: none;
      border-radius: 6px;
      font-size: 16px;
      font-weight: 600;
      cursor: pointer;
      transition: transform 0.2s, box-shadow 0.2s;
    }
    button:hover {
      transform: translateY(-2px);
      box-shadow: 0 10px 20px rgba(102, 126, 234, 0.4);
    }
    button:disabled {
      opacity: 0.6;
      cursor: not-allowed;
      transform: none;
    }
    .message {
      padding: 15px;
      border-radius: 6px;
      margin-bottom: 20px;
      display: none;
    }
    .message.success {
      background: #d4edda;
      color: #155724;
      border: 1px solid #c3e6cb;
    }
    .message.error {
      background: #f8d7da;
      color: #721c24;
      border: 1px solid #f5c6cb;
    }
    .message.show {
      display: block;
    }
    .progress {
      margin-top: 20px;
      padding: 15px;
      background: #f8f9fa;
      border-radius: 6px;
      font-size: 14px;
      line-height: 1.6;
      display: none;
    }
    .progress.show {
      display: block;
    }
    .progress-step {
      color: #666;
      margin-bottom: 5px;
    }
    .progress-step.active {
      color: #667eea;
      font-weight: 600;
    }
    .progress-step.done {
      color: #28a745;
    }
    .next-steps {
      background: #e7f3ff;
      border: 1px solid #b3d9ff;
      border-radius: 6px;
      padding: 20px;
      margin-top: 20px;
    }
    .next-steps h3 {
      color: #0066cc;
      margin-bottom: 10px;
      font-size: 16px;
    }
    .next-steps ol {
      margin-left: 20px;
      color: #333;
      line-height: 1.8;
    }
    .next-steps code {
      background: #f4f4f4;
      padding: 2px 6px;
      border-radius: 3px;
      font-size: 13px;
    }
  </style>
</head>
<body>
  <div class="container">
    <h1>🚀 NREP Project Management System</h1>
    <p class="subtitle">Initial Setup - Create your organization and admin account</p>

    <div id="message" class="message"></div>

    <form id="setupForm">
      <div class="section">
        <div class="section-title">📊 Organization Setup</div>
        <div class="form-group">
          <label for="orgName">Organization Name</label>
          <input type="text" id="orgName" name="orgName" required placeholder="e.g., NREP">
        </div>
      </div>

      <div class="section">
        <div class="section-title">👤 Admin User Account</div>
        <div class="form-group">
          <label for="email">Email Address</label>
          <input type="email" id="email" name="email" required placeholder="admin@nrep.ug">
        </div>
        <div class="form-group">
          <label for="username">Username</label>
          <input type="text" id="username" name="username" required placeholder="admin">
        </div>
        <div class="form-group">
          <label for="firstName">First Name</label>
          <input type="text" id="firstName" name="firstName" required placeholder="John">
        </div>
        <div class="form-group">
          <label for="lastName">Last Name</label>
          <input type="text" id="lastName" name="lastName" required placeholder="Doe">
        </div>
        <div class="form-group">
          <label for="otherNames">Other Names <span class="optional">(optional)</span></label>
          <input type="text" id="otherNames" name="otherNames" placeholder="Middle names">
        </div>
        <div class="form-group">
          <label for="password">Password <span class="optional">(min 8 characters)</span></label>
          <input type="password" id="password" name="password" required minlength="8" placeholder="••••••••">
        </div>
        <div class="form-group">
          <label for="confirmPassword">Confirm Password</label>
          <input type="password" id="confirmPassword" name="confirmPassword" required minlength="8" placeholder="••••••••">
        </div>
      </div>

      <button type="submit" id="submitBtn">Create Organization & Admin Account</button>
    </form>

    <div id="progress" class="progress"></div>
    <div id="nextSteps" style="display: none;"></div>
  </div>

  <script>
    const form = document.getElementById('setupForm');
    const submitBtn = document.getElementById('submitBtn');
    const messageDiv = document.getElementById('message');
    const progressDiv = document.getElementById('progress');
    const nextStepsDiv = document.getElementById('nextSteps');

    function showMessage(text, type) {
      messageDiv.textContent = text;
      messageDiv.className = 'message ' + type + ' show';
    }

    function hideMessage() {
      messageDiv.className = 'message';
    }

    function showProgress(steps) {
      progressDiv.innerHTML = steps.map(step =>
        '<div class="progress-step ' + step.status + '">' + step.text + '</div>'
      ).join('');
      progressDiv.className = 'progress show';
    }

    form.addEventListener('submit', async (e) => {
      e.preventDefault();
      hideMessage();

      const password = document.getElementById('password').value;
      const confirmPassword = document.getElementById('confirmPassword').value;

      if (password !== confirmPassword) {
        showMessage('Passwords do not match!', 'error');
        return;
      }

      if (password.length < 8) {
        showMessage('Password must be at least 8 characters long!', 'error');
        return;
      }

      const formData = {
        orgName: document.getElementById('orgName').value,
        email: document.getElementById('email').value,
        username: document.getElementById('username').value,
        firstName: document.getElementById('firstName').value,
        lastName: document.getElementById('lastName').value,
        otherNames: document.getElementById('otherNames').value,
        password: password
      };

      submitBtn.disabled = true;
      submitBtn.textContent = 'Setting up...';

      showProgress([
        { text: '⏳ Creating organization team...', status: 'active' },
        { text: '⏳ Creating organization document...', status: '' },
        { text: '⏳ Creating admin user account...', status: '' },
        { text: '⏳ Setting up user profile...', status: '' },
        { text: '⏳ Updating configuration files...', status: '' }
      ]);

      try {
        const response = await fetch('/setup', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(formData)
        });

        const result = await response.json();

        if (response.ok) {
          showProgress([
            { text: '✓ Organization team created', status: 'done' },
            { text: '✓ Organization document created', status: 'done' },
            { text: '✓ Admin user account created', status: 'done' },
            { text: '✓ User profile set up', status: 'done' },
            { text: '✓ Configuration files updated', status: 'done' }
          ]);

          showMessage('Setup completed successfully!', 'success');
          form.style.display = 'none';

          nextStepsDiv.innerHTML = \`
            <div class="next-steps">
              <h3>✓ Setup Complete! Next Steps:</h3>
              <ol>
                <li>Close this setup server (Ctrl+C in terminal)</li>
                <li><strong>.env.local has been updated</strong> with your organization info</li>
                <li>Start the dev server: <code>npm run dev</code></li>
                <li>Open <code>http://localhost:3000/login</code></li>
                <li>Log in with email: <strong>\${formData.email}</strong></li>
                <li>Navigate to Admin panel to invite other users</li>
              </ol>
              <p style="margin-top: 15px; padding: 10px; background: #fff3cd; border: 1px solid #ffc107; border-radius: 4px; color: #856404;">
                <strong>📝 Note:</strong> Your <code>.env.local</code> file has been automatically updated with:<br>
                • Organization Name: <strong>\${result.orgName}</strong><br>
                • Organization Team ID: <strong>\${result.orgTeamId}</strong>
              </p>
            </div>
          \`;
          nextStepsDiv.style.display = 'block';

        } else {
          showMessage(result.error || 'Setup failed. Please check the console.', 'error');
          submitBtn.disabled = false;
          submitBtn.textContent = 'Create Organization & Admin Account';
          progressDiv.className = 'progress';
        }
      } catch (error) {
        showMessage('Network error: ' + error.message, 'error');
        submitBtn.disabled = false;
        submitBtn.textContent = 'Create Organization & Admin Account';
        progressDiv.className = 'progress';
      }
    });
  </script>
</body>
</html>
  `);
});

// Handle setup POST
app.post('/setup', async (req, res) => {
  try {
    const { orgName, email, username, firstName, lastName, otherNames, password } = req.body;

    // Validate inputs
    if (!orgName || !email || !username || !firstName || !lastName || !password) {
      return res.status(400).json({ error: 'All required fields must be filled' });
    }

    if (password.length < 8) {
      return res.status(400).json({ error: 'Password must be at least 8 characters' });
    }

    const orgSlug = slugify(orgName);
    const orgTeamId = `org_${orgSlug}`;

    console.log('\n=== Starting Setup ===');
    console.log('Organization:', orgName);
    console.log('Team ID:', orgTeamId);
    console.log('Admin Email:', email);
    console.log('Admin Username:', username);

    // 1. Create team
    console.log('\n→ Creating organization team...');
    const teamResult = await ensureTeam(orgTeamId, orgName);
    if (teamResult.exists) {
      console.log('✓ Team already exists:', orgTeamId);
    } else {
      console.log('✓ Team created:', orgTeamId);
    }

    // 2. Create org document
    console.log('\n→ Creating organization document...');
    const orgResult = await ensureOrgDoc(orgTeamId, orgName);
    if (orgResult.created) {
      console.log('✓ Organization document created:', orgResult.doc.$id);
    } else {
      console.log('✓ Organization document already exists');
    }

    // 3. Create admin user
    console.log('\n→ Creating admin user...');
    const user = await createAdminUser(orgTeamId, {
      email,
      username,
      firstName,
      lastName,
      otherNames,
      password
    });
    console.log('✓ Admin user created:', user.$id);

    // 4. Update .env.local file with organization info
    console.log('\n→ Updating .env.local file...');
    try {
      updateEnvFile(orgName, orgTeamId);
    } catch (envError) {
      console.warn('⚠ Could not update .env.local:', envError.message);
      // Don't fail the setup if env update fails
    }

    console.log('\n=== Setup Complete! ===\n');

    res.json({
      success: true,
      message: 'Setup completed successfully',
      orgTeamId,
      orgName,
      userId: user.$id
    });

  } catch (error) {
    console.error('\n✗ Setup Error:', error);
    console.error('Message:', error.message);
    console.error('Code:', error.code);
    console.error('Type:', error.type);

    let errorMessage = 'Setup failed: ' + error.message;

    if (error.code === 409) {
      errorMessage = 'User with this email already exists. Please use a different email.';
    } else if (error.code === 404) {
      errorMessage = 'Database collections not found. Please run: npm run setup:collections';
    }

    res.status(500).json({
      error: errorMessage,
      code: error.code,
      type: error.type
    });
  }
});

const PORT = 3001;
app.listen(PORT, () => {
  console.log('\n╔═══════════════════════════════════════════════════════════╗');
  console.log('║       NREP Project Management System - Setup              ║');
  console.log('╚═══════════════════════════════════════════════════════════╝');
  console.log('\n🌐 Setup server is running!');
  console.log(`\n   Open your browser and go to:\n`);
  console.log(`   → http://localhost:${PORT}\n`);
  console.log('📝 Fill out the form to create your organization and admin user.');
  console.log('🛑 Press Ctrl+C to stop this server when done.\n');
});
